version: 2
sources:
  - name: raw_ssb
    description: 'Raw data from Statistics Norway (SSB)'
    schema: public
    tables:
      - name: ssb_09190_gdp_quarterly
        description: 'Raw GDP quarterly data from SSB table 09190. Constant 2022 prices, seasonally adjusted.'
        external:
          location: 'https://www.ssb.no/en/statbank/table/09190'
        columns:
          - name: id
            description: 'Primary key'
          - name: period_id
            description: 'Foreign key to time_periods table'
          - name: year_quarter
            description: 'Quarter in YYYYKX format (e.g., 2025K1)'
          - name: gdp_type
            description: 'Type of GDP measure (total or mainland)'
          - name: value_nok_million
            description: 'GDP value in millions of NOK, constant 2022 prices, seasonally adjusted'
          - name: created_at
            description: 'Timestamp when record was created'

      - name: ssb_03013_cpi_by_group
        description: 'Raw CPI data from SSB table 03013'
        columns:
          - name: id
            description: 'Primary key'
          - name: period_id
            description: 'Foreign key to time_periods table'
          - name: year_month
            description: 'Month in YYYYMXX format (e.g., 2025M01)'
          - name: consumption_group
            description: 'CPI consumption group'
          - name: measure_type
            description: 'Type of measure (index, monthly_change, yearly_change)'
          - name: value
            description: 'CPI value (DECIMAL 10,2)'
          - name: created_at
            description: 'Timestamp when record was created'

      - name: ssb_05327_adjusted_cpi_by_group
        description: 'Raw adjusted CPI data from SSB table 05327'
        columns:
          - name: id
            description: 'Primary key'
          - name: period_id
            description: 'Foreign key to time_periods table'
          - name: consumption_group
            description: 'Adjusted CPI consumption group (JA_TOTAL, JAE_TOTAL, etc.)'
          - name: measure_type
            description: 'Type of measure (index, monthly_change, yearly_change)'
          - name: value
            description: 'Adjusted CPI value'
          - name: created_at
            description: 'Timestamp when record was created'

      - name: ssb_09842_gdp_per_capita
        description: 'Raw GDP per capita data from SSB table 09842'
        columns:
          - name: id
            description: 'Primary key'
          - name: period_id
            description: 'Foreign key to time_periods table'
          - name: indicator_name
            description: 'Name of the GDP indicator'
          - name: value_nok_per_capita
            description: 'GDP value per capita in NOK'
          - name: created_at
            description: 'Timestamp when record was created'

      - name: ssb_13760_labour_force_survey
        description: 'Raw labour force survey data from SSB table 13760'
        columns:
          - name: id
            description: 'Primary key'
          - name: period_id
            description: 'Foreign key to time_periods table'
          - name: value
            description: 'Unemployment rate value'
          - name: created_at
            description: 'Timestamp when record was created'

      - name: time_periods
        description: 'Time periods lookup table'
        columns:
          - name: period_id
            description: 'Primary key'
          - name: period_type
            description: 'Type of period (monthly, quarterly, yearly)'
          - name: period_code
            description: 'Period code (e.g., 2025M01, 2025K1)'
          - name: start_date
            description: 'Start date of the period'
          - name: end_date
            description: 'End date of the period'

  - name: raw_nb
    description: 'Raw data from Norges Bank'
    schema: public
    tables:
      - name: nb_mpr_indicators
        description: 'Norges Bank MPR indicators including policy rate'
        columns:
          - name: id
            description: 'Primary key'
          - name: year_month
            description: 'Month in YYYYMXX format (e.g., 2025M03)'
          - name: source
            description: 'Source publication (e.g., PPR 2/25)'
          - name: indicator
            description: 'Type of indicator (e.g., policy_rate)'
          - name: value
            description: 'Indicator value'
          - name: created_at
            description: 'Timestamp when record was created'
      - name: nb_policy_rates_monthly
        description: 'Monthly policy rates from Norges Bank'
        columns:
          - name: id
            description: 'Primary key'
          - name: year_month
            description: 'Month in YYYYMXX format (e.g., 2025M03)'
          - name: instrument_type 
            description: |
              Type of financial instrument. Possible values:
              - KPRA: Key policy rate - The sight deposit rate. The interest rate on banks' reserves up to a specified quota in Norges Bank.
            tests:
              - accepted_values:
                  values: ['KPRA']
          - name: tenor 
            description: |
              The amount of time left for the repayment of a loan or until a financial contract expires. Possible values:
              - OL: Overnight lending rate
              - RR: Reserve rate
              - SD: Sight deposit rate (Policy rate)
            tests:
              - accepted_values:
                  values: ['OL', 'RR', 'SD']
          - name: rate 
            description: 'Interest rate value (DECIMAL format)'
          - name: created_at
            description: 'Timestamp when record was created'
